version: "3"
services:
  web:
    build: .
    container_name: cats_api
    ports:
      - "5000:5000"
    volumes: 
      - cats_logs:/usr/src/logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch      
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.1
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - cats_logs:/cats_app/logs
    depends_on:
      - elasticsearch
    networks: 
      - elastic

volumes:
  data01:
    driver: local
  cats_logs:
    driver: local

networks:
  elastic:
    driver: bridge